# Unique project identifier and organization keys for SonarCloud/SonarQube
sonar.projectKey=kushalsk99_SelfHealing-Kubernetes-Cluster
sonar.organization=kushalsk99

# Metadata displayed in the dashboard interface
sonar.projectName=SelfHealing-Kubernetes-Cluster
sonar.projectVersion=1.0

# Path to the source code analysis target
sonar.sources=.
sonar.exclusions=**/*_test.go, **/vendor/**

# Language specific compiler settings
sonar.go.exclusions=**/vendor/**
